"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { motion } from "framer-motion";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import { CheckCircle, Download, Phone, ChevronRight, Quote } from "lucide-react";
import Navbar from "../../../../components/Navbar";
import Footer from "../../../../components/Footer";

const growthColor = (outlook) => {
  if (!outlook) return "text-white/50 bg-white/5 border-white/10";
  const o = outlook.toLowerCase();
  if (o.includes("high")) return "text-green-400 bg-green-400/10 border-green-400/20";
  if (o.includes("medium")) return "text-yellow-400 bg-yellow-400/10 border-yellow-400/20";
  return "text-red-400 bg-red-400/10 border-red-400/20";
};

export default function RoadmapClient() {
  const router = useRouter();
  const [data, setData] = useState(null);
  const [userName, setUserName] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchRoadmap = async () => {
      try {
        // Try user info from localStorage
        try {
          const user = JSON.parse(localStorage.getItem("user") || "{}");
          if (user.name) setUserName(user.name);
        } catch {}

        const token = localStorage.getItem("token");
        if (!token) {
          router.replace("/login?redirect=/ability-test/roadmap");
          return;
        }

        // 1. Try sessionStorage cache first for instant load
        const cached = sessionStorage.getItem("roadmapData");
        if (cached) {
          setData(JSON.parse(cached));
          setLoading(false);
          return;
        }

        // 2. Fetch from MongoDB
        const res = await fetch("http://localhost:5000/api/roadmap/my", {
          headers: { "Authorization": `Bearer ${token}` },
        });
        const json = await res.json();

        if (json.success && json.roadmap?.data) {
          sessionStorage.setItem("roadmapData", JSON.stringify(json.roadmap.data));
          setData(json.roadmap.data);
        } else {
          setError("No roadmap found. Please take the ability test first.");
        }
      } catch (err) {
        console.error("Roadmap fetch error:", err);
        setError("Failed to load your roadmap. Please try again.");
      } finally {
        setLoading(false);
      }
    };

    fetchRoadmap();
  }, [router]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#09090b] flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 border-2 border-[#0EB4A6] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-white/50 text-sm">Loading your roadmap...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen bg-[#09090b] flex flex-col items-center justify-center text-white px-4">
        <div className="bg-[#121214] border border-white/10 rounded-2xl p-10 max-w-md text-center">
          <p className="text-white/50 mb-6">{error || "No roadmap found."}</p>
          <Link href="/ability-test" className="px-6 py-3 bg-[#0EB4A6] text-white rounded-full font-bold text-sm hover:bg-[#0c9c90] transition-colors">
            Take the Ability Test
          </Link>
        </div>
      </div>
    );
  }

  const { studentProfile, topCareers, recommendedCourses, roadmapSteps, immediateNextSteps, motivationalNote } = data;

  return (
    <div className="min-h-screen bg-[#09090b] text-white font-sans overflow-x-hidden">
      <Navbar />

      <main className="pt-32 pb-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Header */}
        <div className="text-center mb-16">
          <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#0EB4A6]/10 border border-[#0EB4A6]/20 text-xs font-bold text-[#0EB4A6] tracking-wider mb-4">
            Generated by AI · Personalised for You
          </span>
          <h1 className="text-4xl md:text-5xl font-bold mb-3">Your Personalised Career Roadmap</h1>
          <p className="text-white/60 text-lg max-w-2xl mx-auto">Based on your ability test results, here is your AI-generated career path.</p>
        </div>

        {/* Student Profile Card */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-[#121214] border border-white/5 rounded-2xl p-6 mb-8">
          <h2 className="text-xl font-bold mb-5">Your Profile</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <p className="text-xs text-white/40 mb-2">Dominant Traits</p>
              <div className="flex flex-wrap gap-2">
                {(studentProfile?.dominantTraits || []).map((t, i) => (
                  <span key={i} className="bg-[#0EB4A6]/10 border border-[#0EB4A6]/20 text-[#0EB4A6] text-xs px-3 py-1.5 rounded-full">{t}</span>
                ))}
              </div>
            </div>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-white/40">Learning Style</p>
                <p className="text-sm text-white/70">{studentProfile?.learningStyle}</p>
              </div>
              <div>
                <p className="text-xs text-white/40">Work Style</p>
                <p className="text-sm text-white/70">{studentProfile?.workStyle}</p>
              </div>
            </div>
            <div className="md:col-span-2">
              <p className="text-xs text-white/40 mb-2">Strengths</p>
              <div className="flex flex-wrap gap-2">
                {(studentProfile?.strengths || []).map((s, i) => (
                  <span key={i} className="flex items-center gap-1 text-xs text-white/60 bg-white/5 border border-white/5 px-3 py-1.5 rounded-full">
                    <CheckCircle className="w-3 h-3 text-[#0EB4A6]" /> {s}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Top Career Matches */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Top Career Matches</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {(topCareers || []).map((career, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="bg-[#121214] border border-white/5 rounded-2xl p-6 hover:border-[#0EB4A6]/30 transition-all relative">
                {i === 0 && <span className="absolute top-4 right-4 text-xs bg-[#0EB4A6] text-black font-bold px-2 py-1 rounded-md">BEST MATCH</span>}
                <div className="w-20 h-20 mx-auto mb-4">
                  <CircularProgressbar value={career.matchPercentage || 0} text={`${career.matchPercentage}%`}
                    styles={buildStyles({ textSize: "18px", textColor: "#0EB4A6", pathColor: "#0EB4A6", trailColor: "rgba(255,255,255,0.05)" })} />
                </div>
                <h3 className="text-lg font-bold text-center mb-1">{career.title}</h3>
                <div className="flex items-center justify-center gap-2 mb-4">
                  <span className="text-xs bg-white/5 border border-white/10 px-2 py-1 rounded-full text-white/50">{career.field}</span>
                  <span className={`text-xs border px-2 py-1 rounded-full ${growthColor(career.growthOutlook)}`}>{career.growthOutlook}</span>
                </div>
                <p className="text-white/50 text-sm mb-4 text-center">{career.description}</p>
                <div className="text-center mb-4">
                  <p className="text-xs text-white/30 mb-1">Average Salary</p>
                  <p className="font-bold text-[#0EB4A6]">{career.averageSalary}</p>
                </div>
                <div className="flex flex-wrap gap-1.5 justify-center">
                  {(career.keySkills || []).map((sk, j) => (
                    <span key={j} className="text-xs bg-white/5 border border-white/5 px-2 py-1 rounded-md text-white/40">{sk}</span>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Recommended Courses */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Recommended Courses</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {(recommendedCourses || []).map((course, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="bg-[#121214] border border-white/5 rounded-2xl p-6">
                <h3 className="font-bold text-lg mb-1">{course.degree}</h3>
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-xs text-white/40 bg-white/5 px-2 py-1 rounded-md">{course.type}</span>
                  <span className="text-xs text-[#0EB4A6]">{course.duration}</span>
                </div>
                <p className="text-xs text-white/40 mb-2">Top Colleges</p>
                <ul className="space-y-1.5">
                  {(course.topColleges || []).map((col, j) => (
                    <li key={j} className="flex items-center gap-2 text-sm text-white/60">
                      <span className="w-1.5 h-1.5 rounded-full bg-[#0EB4A6]" /> {col}
                    </li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Career Roadmap Timeline */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-8">Your Step-by-Step Roadmap</h2>
          <div className="relative">
            <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-[#0EB4A6]/30" />
            <div className="space-y-8">
              {(roadmapSteps || []).map((step, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                  className="relative pl-16">
                  <div className="absolute left-3 top-5 w-6 h-6 rounded-full bg-[#0EB4A6] flex items-center justify-center text-black text-xs font-bold -translate-x-1/2">
                    {i + 1}
                  </div>
                  <div className="bg-[#121214] border border-white/5 rounded-2xl p-6">
                    <span className="text-xs text-[#0EB4A6] font-bold">{step.phase}</span>
                    <h3 className="font-bold text-lg mb-2 mt-1">{step.title}</h3>
                    <p className="text-white/50 text-sm mb-4">{step.description}</p>
                    <ul className="space-y-2 mb-4">
                      {(step.actions || []).map((action, j) => (
                        <li key={j} className="flex items-start gap-2 text-sm text-white/60">
                          <CheckCircle className="w-4 h-4 text-[#0EB4A6] mt-0.5 flex-shrink-0" /> {action}
                        </li>
                      ))}
                    </ul>
                    <div className="bg-[#0EB4A6]/10 border border-[#0EB4A6]/20 rounded-xl px-4 py-3">
                      <p className="text-xs text-[#0EB4A6] font-bold mb-0.5">🎯 Milestone</p>
                      <p className="text-sm text-[#0EB4A6]/80">{step.milestone}</p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* Immediate Next Steps */}
        <div className="mb-8">
          <div className="bg-[#121214] border border-white/5 rounded-2xl p-6">
            <h2 className="text-2xl font-bold mb-6">Start Today – Your Next 3 Steps</h2>
            <ol className="space-y-4">
              {(immediateNextSteps || []).map((step, i) => (
                <li key={i} className="flex items-start gap-4">
                  <div className="w-8 h-8 rounded-full bg-[#0EB4A6] flex items-center justify-center text-black font-bold text-sm flex-shrink-0">{i + 1}</div>
                  <p className="text-white/70 pt-1">{step}</p>
                </li>
              ))}
            </ol>
          </div>
        </div>

        {/* Motivational Note */}
        {motivationalNote && (
          <div className="mb-8 bg-gradient-to-r from-[#0EB4A6]/20 to-transparent border border-[#0EB4A6]/30 rounded-2xl p-6">
            <Quote className="w-8 h-8 text-[#0EB4A6] mb-3" />
            <p className="text-lg text-white/80 italic leading-relaxed">{motivationalNote}</p>
            {userName && <p className="text-sm text-[#0EB4A6] mt-3 font-medium">— Personalised for {userName}</p>}
          </div>
        )}

        {/* Contact CTA */}
        <div className="bg-[#121214] border border-white/5 rounded-2xl p-8 text-center mb-8">
          <h2 className="text-2xl font-bold mb-2">Want personalised guidance from an expert counselor?</h2>
          <p className="text-white/50 mb-6">Our certified counselors are available to walk you through your roadmap and answer every question.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a href="tel:+919876543210" className="bg-[#0EB4A6] text-black font-bold px-8 py-4 rounded-full flex items-center gap-2 justify-center hover:bg-[#0c9c90] transition-colors shadow-[0_0_20px_rgba(14,180,166,0.3)]">
              <Phone className="w-5 h-5" /> Call Us: +91-98765-43210
            </a>
            <Link href="/counseling" className="border border-white/20 text-white font-medium px-8 py-4 rounded-full flex items-center gap-2 justify-center hover:bg-white/5 transition-colors">
              Book a Counseling Session <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
        </div>

        {/* Download */}
        <div className="text-center">
          <button onClick={() => window.print()} className="border border-white/10 text-white/50 hover:text-white hover:border-white/20 px-6 py-3 rounded-full text-sm flex items-center gap-2 mx-auto transition-all">
            <Download className="w-4 h-4" /> Download Roadmap
          </button>
        </div>
      </main>

      <Footer />
    </div>
  );
}
